### ISSUE TITLE
Modify: write info about star file and populate Master key at end of Modify -> Rotate... and -> Rotate Manually.

### ISSUE THREAD

**Issue by axelbrunger** [brungerlab/pycresta#11]
Modify: write info about star file and populate Master key at end of Modify -> Rotate... and -> Rotate Manually.

**Comment by psliz05** [comment]
Confirming this issue: Should the newly created starfile have angles and shifts all set to 0, since the rotation has been applied? And then this new starfile populated to master key?

**Comment by psliz05** [comment]
New star file is created and populates the unfiltered star file path on master key. The star file name is labeled with the original name + rottrans + the current timestamp
