### ISSUE TITLE
coordinate readers do not read floating point numbers

### ISSUE THREAD

**Issue by axelbrunger** [brungerlab/pycresta#31]
The coordinate readers for the Extract task only read integers. They fail for floating-point input.

**Comment by psliz05** [comment]
does this mean we do **not** want to include this rounding to integer code?
`# rounding`
 `bound = np.round(bound).astype(int)`
 `z = np.round(z).astype(int)`
 `y = np.round(y).astype(int)`
 `x = np.round(x).astype(int)`

**Comment by psliz05** [comment]
fixed — floating point and scientific notation should now be read
