### ISSUE TITLE
Filtering (Gaussian option). Filtering: Each time pycresta creates a new directory with subtomograms, please write all information about settings and inputs as a text  file into that directory, i.e., project text file.

### ISSUE THREAD

**Issue by axelbrunger** [brungerlab/pycresta#5]
So, if the user performs filtering, the file should contain the information about the particular settings and inputs that were used for the filtering job. Is OK for Wiener option, but please also do for Gaussian.

**Comment by mldylai** [comment]
Project text file added, let me know if it works on your end!

**Comment by axelbrunger** [comment]
Thank you. It works well. However, ideally, these .txt files should be put in the respective directory where the new filtered subtomogram mrc files are stored. Is this possible? Thank you.

**Comment by axelbrunger** [comment]
Thank you. It works well. However, ideally, these .txt files should be put in the respective directory where the new filtered subtomogram mrc files are stored. Is this possible? Thank you.

On Aug 16, 2023, at 2:31 AM, Melody Lai ***@***.***> wrote:



Project text file added, let me know if it works on your end!

**Comment by mldylai** [comment]
Yes this is possible, I moved the text files into the respective directories, let me know if it works for you!

**Comment by axelbrunger** [comment]
Thank  you. This works great now.
